### ISSUE TITLE
Regression in 0.11.1: table detail 500s — compute_delta subtracts oldest_snapshot_at, which is a String

### ISSUE THREAD

**Issue by maltzsama** [maltzsama/deepdiver#203]
## Summary

Regression introduced by #200. The table detail page returns **500** on every table whose last maintenance run produced a before/after comparison. `compute_delta` performs arithmetic on `oldest_snapshot_at`, which is persisted as an ISO8601 **String**, raising `undefined method '-' for an instance of String`.

## Evidence (live, 0.11.1)

```
/iceberg_tables/1 -> undefined method '-' for an instance of String
/iceberg_tables/3 -> undefined method '-' for an instance of String
```

```
app/helpers/application_helper.rb:684  ApplicationHelper#compute_delta
app/helpers/application_helper.rb:630  block in ApplicationHelper#table_metric_rows
app/helpers/application_helper.rb:624  ApplicationHelper#table_metric_rows
app/helpers/application_helper.rb:552  ApplicationHelper#metadata_diff
app/views/iceberg_tables/_maintenance_impact.html.erb:20
```

The offending metric, from a real execution's snapshots:

```
total_data_files     before=4689                     (Integer)
total_size_bytes     before=nil                      (NilClass)
snapshot_count       before=182                      (Integer)
oldest_snapshot_at   before="2026-08-28T12:57:08Z"   (String)
```

## Root cause

`compute_delta` (`app/helpers/application_helper.rb:679-691`) subtracts unconditionally once both values are non-nil:

```ruby
def compute_delta(key, old_val, new_val)
  return nil if old_val.nil? && new_val.nil?
  return { direction: :new, magnitude: format_metric_value(key, new_val) } if old_val.nil?
  return { direction: :down, magnitude: format_metric_value(key, old_val) } if new_val.nil?

  diff = new_val - old_val        # <-- String here for oldest_snapshot_at
  return nil if diff.zero?
```

`oldest_snapshot_at` is one of the metrics `expire_snapshots` tracks:

```ruby
"expire_snapshots" => %w[snapshot_count oldest_snapshot_at],
```

and `IcebergTable#metadata_snapshot` serialises it as `oldest_snapshot_at&.iso8601` — a String. `format_metric_value` already knows this and handles it explicitly:

```ruby
when "oldest_snapshot_at" then value.is_a?(String) ? Time.parse(value).to_fs(:short) : value.to_fs(:short)
```

but `compute_delta` was rewritten for #200 without the equivalent guard. The pre-#200 version had the same structural gap, but reached `number_with_delimiter(diff)` rather than `diff.zero?`, and in practice `oldest_snapshot_at` rarely changed — the #196 fix (rendering unchanged metrics, and selecting an execution that actually has a comparison) is what made this path reliably reachable.

## Suggested fix

Handle timestamps explicitly, mirroring `format_metric_value`:

```ruby
def compute_delta(key, old_val, new_val)
  return nil if old_val.nil? && new_val.nil?
  return { direction: :new, magnitude: format_metric_value(key, new_val) } if old_val.nil?
  return { direction: :down, magnitude: format_metric_value(key, old_val) } if new_val.nil?

  if key == "oldest_snapshot_at"
    old_t = old_val.is_a?(String) ? Time.parse(old_val) : old_val
    new_t = new_val.is_a?(String) ? Time.parse(new_val) : new_val
    seconds = (new_t - old_t).round
    return nil if seconds.zero?

    # A newer oldest-snapshot means expire_snapshots removed history: an improvement.
    return { direction: seconds.positive? ? :down : :up,
             magnitude: distance_of_time_in_words(seconds.abs) }
  end

  diff = new_val - old_val
  return nil if diff.zero?
  ...
```

Note the direction is inverted relative to the numeric metrics: for `oldest_snapshot_at`, the value moving **forward** in time means old snapshots were expired, which is the desired outcome — so it should read as `:down` (improvement, `--ok`) even though the underlying value increased. Treating it like the others would colour a successful `expire_snapshots` amber.

A defensive `return nil unless old_val.is_a?(Numeric) && new_val.is_a?(Numeric)` before the subtraction would also prevent any future non-numeric metric from taking down the page, which matters because this code path renders inside a view with no rescue.

## Impact

The table detail page is unreachable (HTTP 500) for every table that has a completed maintenance run with a before/after snapshot — i.e. exactly the tables an operator most needs to inspect. Both tables on this deployment with maintenance history are affected.
